// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoinTransfer struct {
	ID           int32
	FromUsername string
	ToUsername   string
	Amount       int32
	CreatedAt    pgtype.Timestamptz
}

type Product struct {
	Item  string
	Price int32
}

type Purchase struct {
	ID        int32
	Username  string
	Item      string
	Price     int32
	CreatedAt pgtype.Timestamptz
}

type User struct {
	Username     string
	PasswordHash string
	Coins        int32
}
